config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpdesk.urls')),
]

helpdesk/urls.py
from django.contrib.auth import views
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken import views as rest_views

from helpdesk.API.resourses import RegistrationViewSet, TicketViewSet, CommentViewSet,\
    RestoreTicketViewSet
from helpdesk.views import UserCreateView, TicketCreateView, TicketUpdateView,\
    TicketListView, TicketDetailView, CommentCreateView, ChangeTicketStatusView,\
    RestoreTicketListView


router = routers.SimpleRouter()
router.register(r'registration', RegistrationViewSet)
router.register(r'ticket', TicketViewSet)
router.register(r'restore-ticket', RestoreTicketViewSet)
router.register(r'comment', CommentViewSet)

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('', TicketListView.as_view(), name='home'),
    path('restore-ticket', RestoreTicketListView.as_view(), name='restore_ticket'),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='detail_ticket'),
    path('add-ticket/', TicketCreateView.as_view(), name='add_ticket'),
    path('update-ticket/<int:pk>/', TicketUpdateView.as_view(), name='update_ticket'),
    path('update-ticket-status/<int:pk>/', ChangeTicketStatusView.as_view(), name='change_status'),
    path('add-comment/<int:pk>', CommentCreateView.as_view(), name='add_comment'),

    path('api/', include(router.urls)),
    path('api/get-auth-token/', rest_views.obtain_auth_token)
]

helpdesk/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    first_name = models.CharField('first name', max_length=150)
    last_name = models.CharField('last name', max_length=150)
    email = models.EmailField(unique=True)

    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']


class Ticket(models.Model):
    HIGH_PRIORITY = 1
    MEDIUM_PRIORITY = 2
    LOW_PRIORITY = 3

    PRIORITY_CHOICES = [
        (HIGH_PRIORITY, 'High'),
        (MEDIUM_PRIORITY, 'Medium'),
        (LOW_PRIORITY, 'Low'),
    ]

    ACTIVE_STATUS = 1
    PROCESSED_STATUS = 2
    REJECTED_STATUS = 3
    RESTORED_STATUS = 4
    COMPLETED_STATUS = 5

    STATUS_CHOICES = [
        (ACTIVE_STATUS, 'Active'),
        (PROCESSED_STATUS, 'Processed'),
        (REJECTED_STATUS, 'Rejected'),
        (RESTORED_STATUS, 'Restored'),
        (COMPLETED_STATUS, 'Completed'),
    ]

    user = models.ForeignKey(CustomUser, related_name='tickets', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    priority = models.PositiveSmallIntegerField(choices=PRIORITY_CHOICES, default=MEDIUM_PRIORITY)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=ACTIVE_STATUS)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']
        verbose_name = 'ticket'
        verbose_name_plural = 'tickets'

    def __str__(self):
        return self.title


class Comment(models.Model):
    DISCUSSION_TOPIC = 1
    REJECT_TOPIC = 2
    RESTORE_TOPIC = 3

    TOPIC_CHOICES = [
        (DISCUSSION_TOPIC, 'Discussion'),
        (REJECT_TOPIC, 'Reject'),
        (RESTORE_TOPIC, 'Restore'),
    ]

    author = models.ForeignKey(CustomUser, related_name='comments', on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, related_name='comments', on_delete=models.CASCADE)
    topic = models.PositiveSmallIntegerField(choices=TOPIC_CHOICES, default=DISCUSSION_TOPIC)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.body

helpdesk/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import HiddenInput

from helpdesk.models import CustomUser, Ticket, Comment


class UserCreateForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts = {
            'username': None,
        }


class CommentCreateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['body']

    def __init__(self, *args, **kwargs):
        self.ticket = kwargs.pop('ticket', None)
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        super().clean()
        current_status = self.ticket.status
        ticket_author = self.ticket.user
        comment_author = self.request.user

        if current_status != Ticket.ACTIVE_STATUS:
            self.add_error(None, 'You cannot comment on an ticket that is not in the active status.')

        if ticket_author != comment_author and not comment_author.is_staff:
            self.add_error(None, 'Only the author or administrator can leave a comment on the ticket.')


class TicketUpdateForm(forms.ModelForm):

    class Meta:
        model = Ticket
        fields = ['description', 'priority']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        super().clean()
        current_status = self.instance.status
        author = self.instance.user
        user = self.request.user

        if current_status != Ticket.ACTIVE_STATUS:
            self.add_error(None, 'You cannot edit an ticket if it is not in the Active status.')

        if author != user:
            self.add_error(None, 'You can change only your ticket.')


class ChangeTicketStatusForm(forms.ModelForm):
    comment = forms.CharField(required=False, widget=forms.Textarea)

    class Meta:
        model = Ticket
        fields = ['status']
        widgets = {
            'status': HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        changed_status = cleaned_data.get('status')
        current_status = self.instance.status
        author = self.instance.user
        user = self.request.user
        user_is_admin = user.is_staff

        if user != author and not user_is_admin:
            self.add_error('status', 'You can change status only your ticket.')

        elif changed_status == current_status:
            self.add_error('status', 'Status should be different.')

        elif changed_status == Ticket.ACTIVE_STATUS:
            self.add_error('status', 'Status ACTIVE cannot be set by user.')

        elif changed_status in [Ticket.PROCESSED_STATUS, Ticket.REJECTED_STATUS]:
            if not user_is_admin:
                self.add_error('status', 'Status can only be changed by the administrator.')
            elif current_status not in [Ticket.ACTIVE_STATUS, Ticket.RESTORED_STATUS]:
                self.add_error('status', 'Status can only be changed if the ticket is active or restored.')

        elif changed_status == Ticket.RESTORED_STATUS:
            if user_is_admin:
                self.add_error('status', 'Administrator cant restore tickets.')
            elif current_status != Ticket.REJECTED_STATUS:
                self.add_error('status', 'You can only restore an ticket if it was rejected.')

        elif changed_status == Ticket.COMPLETED_STATUS:
            if not user_is_admin:
                self.add_error('status', 'Status can only be changed by the administrator.')
            elif current_status != Ticket.PROCESSED_STATUS:
                self.add_error('status', 'You can complete the ticket only if it in the status PROCESSED.')

helpdesk/views.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from django.contrib import messages

from helpdesk.filters import TicketFilter
from helpdesk.forms import UserCreateForm, ChangeTicketStatusForm, CommentCreateForm, TicketUpdateForm
from helpdesk.models import Ticket, Comment


class UserCreateView(CreateView):
    form_class = UserCreateForm
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        valid = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return valid


class TicketCreateView(UserPassesTestMixin, CreateView):
    model = Ticket
    fields = ['title', 'description', 'priority']
    template_name = 'helpdesk/ticket_create.html'
    success_url = reverse_lazy('home')

    def test_func(self):
        user = self.request.user
        return user.is_authenticated and not user.is_staff

    def form_valid(self, form):
        ticket = form.save(commit=False)
        user = self.request.user
        ticket.user = user
        ticket.save()
        return super().form_valid(form)


class TicketUpdateView(UserPassesTestMixin, UpdateView):
    model = Ticket
    form_class = TicketUpdateForm
    template_name = 'helpdesk/ticket_update.html'

    def test_func(self):
        ticket = self.get_object()
        user = self.request.user
        return ticket.user == user and ticket.status == Ticket.ACTIVE_STATUS

    def get_success_url(self):
        return reverse_lazy('detail_ticket', kwargs={'pk': self.object.pk})

    def form_invalid(self, form):
        error_list = form.errors.get('__all__')
        for error in error_list:
            messages.error(self.request, error)
        return HttpResponseRedirect(reverse_lazy('home'))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class TicketListView(LoginRequiredMixin, ListView):
    queryset = Ticket.objects.exclude(status=Ticket.RESTORED_STATUS)
    template_name = 'helpdesk/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = TicketFilter(self.request.GET, queryset=self.get_queryset())
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_staff:
            return queryset.filter(user=user)
        return queryset.exclude(status=Ticket.REJECTED_STATUS)


class RestoreTicketListView(UserPassesTestMixin, ListView):
    queryset = Ticket.objects.filter(status=Ticket.RESTORED_STATUS)
    template_name = 'helpdesk/ticket_restore.html'

    def test_func(self):
        return self.request.user.is_staff


class TicketDetailView(UserPassesTestMixin, DetailView):
    model = Ticket
    template_name = 'helpdesk/ticket_detail.html'
    comment_form = CommentCreateForm
    accept_form = ChangeTicketStatusForm(initial={'status': Ticket.PROCESSED_STATUS})
    reject_form = ChangeTicketStatusForm(initial={'status': Ticket.REJECTED_STATUS})
    complete_form = ChangeTicketStatusForm(initial={'status': Ticket.COMPLETED_STATUS})
    restore_form = ChangeTicketStatusForm(initial={'status': Ticket.RESTORED_STATUS})

    def test_func(self):
        ticket = self.get_object()
        user = self.request.user
        return ticket.user == user or user.is_staff

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ticket_status = self.object.status
        user_is_admin = self.request.user.is_staff

        if ticket_status == Ticket.ACTIVE_STATUS:
            context['comment_form'] = self.comment_form

        if ticket_status in [Ticket.ACTIVE_STATUS, Ticket.RESTORED_STATUS] and user_is_admin:
            self.accept_form.fields['comment'].widget = forms.HiddenInput()
            context['accept_form'] = self.accept_form

            if ticket_status == Ticket.ACTIVE_STATUS:
                self.reject_form.fields['comment'].required = True
                self.reject_form.fields['comment'].widget = forms.Textarea()
                context['reject_form'] = self.reject_form

            elif ticket_status == Ticket.RESTORED_STATUS:
                self.reject_form.fields['comment'].required = False
                self.reject_form.fields['comment'].widget = forms.HiddenInput()
                context['reject_form'] = self.reject_form

        if ticket_status == Ticket.PROCESSED_STATUS and user_is_admin:
            self.complete_form.fields['comment'].widget = forms.HiddenInput()
            context['complete_form'] = self.complete_form

        if ticket_status == Ticket.REJECTED_STATUS and not user_is_admin:
            context['restore_form'] = self.restore_form
        return context


class ChangeTicketStatusView(LoginRequiredMixin, UpdateView):
    model = Ticket
    form_class = ChangeTicketStatusForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        ticket = Ticket.objects.get(id=self.object.pk)
        current_status = ticket.status
        changed_status = form.cleaned_data.get('status')
        comment = form.cleaned_data.get('comment')

        if changed_status == Ticket.RESTORED_STATUS and comment:
            with transaction.atomic():
                form.save()
                Comment.objects.create(author=self.request.user,
                                       ticket=self.object,
                                       topic=Comment.RESTORE_TOPIC,
                                       body=comment)
            return HttpResponseRedirect(self.success_url)

        if changed_status == Ticket.REJECTED_STATUS and current_status == Ticket.ACTIVE_STATUS:
            with transaction.atomic():
                form.save()
                Comment.objects.create(author=self.request.user,
                                       ticket=self.object,
                                       topic=Comment.REJECT_TOPIC,
                                       body=comment)
            return HttpResponseRedirect(self.success_url)

        if changed_status == Ticket.REJECTED_STATUS and current_status == Ticket.RESTORED_STATUS:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)

        return super().form_valid(form)

    def form_invalid(self, form):
        error_list = form.errors.get('status')
        for error in error_list:
            messages.error(self.request, error)
        return HttpResponseRedirect(self.success_url)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateView(LoginRequiredMixin, CreateView):
    form_class = CommentCreateForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.ticket = form.ticket
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        error_list = form.errors.get('__all__')
        for error in error_list:
            messages.error(self.request, error)
        return HttpResponseRedirect(reverse_lazy('home'))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        ticket_id = self.kwargs.get('pk')
        ticket = Ticket.objects.get(id=ticket_id)
        kwargs['ticket'] = ticket
        kwargs['request'] = self.request
        return kwargs

    def get_success_url(self):
        return reverse_lazy('detail_ticket', kwargs={'pk': self.object.ticket_id})

helpdesk/templates/helpdesk/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'helpdesk/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&family=Play:wght@400;700&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="main">
        {% include 'includes/header.html' %}
        {% include 'includes/sidebar.html' %}
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
        {% include 'includes/footer.html' %}
    </div>

</body>
</html>

helpdesk/templates/helpdesk/create_ticket.html
{% extends 'helpdesk/base.html' %}
{% block title %}Create Ticket{% endblock %}
{% block content %}
    <div class="main_form">
    <h2>Create Ticket</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    </div>
{% endblock %}

helpdesk/templates/helpdesk/home.html
{% extends 'helpdesk/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}

    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="error-message">
                <p>{{ message }}</p>
            </div>
        {% endif %}
    {% endfor %}

    {% for ticket in filter.qs %}
        <div class="ticket-list" id="{{ ticket.get_status_display|lower }}"
             ondblclick="document.location.href = 'http://127.0.0.1:8000/ticket/' + {{ ticket.id }}">
            <h3>{{ ticket.title }}</h3>
            <p class="ticket-status" id="status-{{ ticket.get_status_display|lower }}">{{ ticket.get_status_display }}</p>
            <div class="ticket-item">
                {% if user.is_staff %}
                <p>Author: {{ ticket.user.get_full_name }}</p>
                {% endif %}
                <p>Creation date: {{ ticket.created|date:'d-M-Y H:i' }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

helpdesk/templates/helpdesk/ticket_create.html
{% extends 'helpdesk/base.html' %}
{% load django_bootstrap5 %}
{% block title %}Create Ticket{% endblock %}
{% block content %}
    <div class="create-form">
    <h2>Create Ticket</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='vertical'%}
        {% bootstrap_button "Create" button_type="submit" button_class="btn-success"%}
    </form>
    </div>
{% endblock %}

helpdesk/templates/helpdesk/ticket_detail.html
{% extends 'helpdesk/base.html' %}
{% load django_bootstrap5 %}
{% block title %}Ticket detail{% endblock %}
{% block content %}
    <div class="ticket-detail" id="{{ ticket.get_status_display|lower }}">
        {% if not user.is_staff and ticket.status == 1 %}
            <p class="update-button"><a href="{% url 'update_ticket' ticket.id %}">Update</a></p>
        {% endif %}

        <p>Title: {{ ticket.title }}</p>
        <p>Description: {{ ticket.description }}</p>
        <p>Priority: {{ ticket.get_priority_display }}</p>
        <p>Status: {{ ticket.get_status_display }}</p>
        {% if user.is_staff %}
            <p>Author: {{ ticket.user.get_full_name }}</p>
        {% endif %}
        <p>Creation date: {{ ticket.created|date:'d-M-Y H:i' }}</p>
        <p>ID: {{ ticket.id }}</p>

        {% if ticket.comments.all %}
        <div class="ticket-comments-block">
            <p id="comment-title">Comments</p>
            {% for comment in ticket.comments.all%}
                {% if comment.topic == 1 %}
                    <div class="ticket-comment admin-{{ comment.author.is_staff|lower }}">
                        <p>{{ comment }}</p>
                        <span>{{ comment.author.get_full_name }}</span>
                        <span>{{ comment.created|date:'d-M-Y H:i' }}</span>
                    </div>
                {% else %}
                    <div class="ticket-comment comment-{{ comment.get_topic_display|lower }}">
                        <p id="topic-name">{{ comment.get_topic_display|upper }}</p>
                        <p>{{ comment }}</p>
                        <span>{{ comment.created|date:'d-M-Y H:i' }}</span>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        {% if comment_form %}
            <div class="comment_form">
                <form action="{% url 'add_comment' ticket.id %}" method="post">
                {% csrf_token %}
                {% for field in comment_form %}
                    {% bootstrap_field field placeholder='leave a comment here...' %}
                {% endfor %}
                {% bootstrap_button "Post comment" button_type="submit" button_class="btn-secondary" %}
                </form>
            </div>
        {% endif %}

        {% if reject_form %}
            <div class="reject_form">
                <form action="{% url 'change_status' ticket.id %}" method="post">
                {% csrf_token %}
                {% for field in reject_form %}
                    {% bootstrap_field field placeholder='enter the reason for rejection here...' %}
                {% endfor %}
                {% bootstrap_button "Reject" button_type="submit" button_class="btn-danger" %}
                </form>
            </div>
        {% endif %}

        {% if accept_form %}
            <div class="accept_form">
                <form action="{% url 'change_status' ticket.id %}" method="post">
                {% csrf_token %}
                {% bootstrap_form accept_form %}
                {% bootstrap_button "Accept" button_type="submit" button_class="btn-success"%}
                </form>
            </div>
        {% endif %}

        {% if complete_form %}
            <div class="complete_form">
                <form action="{% url 'change_status' ticket.id %}" method="post">
                {% csrf_token %}
                {% bootstrap_form complete_form %}
                {% bootstrap_button "Complete" button_type="submit" button_class="btn-primary"%}
                </form>
            </div>
        {% endif %}

        {% if restore_form %}
            <div class="restore_form">
                <form action="{% url 'change_status' ticket.id %}" method="post">
                {% csrf_token %}
                {% for field in restore_form %}
                    {% bootstrap_field field placeholder='enter a comment on re-applying here...' %}
                {% endfor %}
                {% bootstrap_button "Restore" button_type="submit" button_class="btn-success"%}
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}

helpdesk/templates/helpdesk/ticket_restore.html
{% extends 'helpdesk/base.html' %}
{% block title %}Restore ticket{% endblock %}
{% block content %}

    {% for ticket in object_list %}
        <div class="ticket-list" id="{{ ticket.get_status_display|lower }}"
             ondblclick="document.location.href = 'http://127.0.0.1:8000/ticket/' + {{ ticket.id }}">
            <h3>{{ ticket.title }}</h3>
            <p class="ticket-status" id="status-{{ ticket.get_status_display|lower }}">{{ ticket.get_status_display }}</p>
            <div class="ticket-item">
                <p class="ticket-item">Author: {{ ticket.user.get_full_name }}</p>
                <p class="ticket-item">Creation date: {{ ticket.created|date:'d-M-Y H:i' }}</p>
            </div>
        </div>
    {% endfor %}

{% endblock %}

helpdesk/templates/helpdesk/ticket_update.html
{% extends 'helpdesk/base.html' %}
{% load django_bootstrap5 %}
{% block title %}Update ticket{% endblock %}
{% block content %}
<div class="update-form">
    <form action="" method="post">
        {% csrf_token %}
        <h1>Update tiket</h1>
        {% bootstrap_form form layout='vertical'%}
        {% bootstrap_button "Update" button_type="submit" button_class="btn-success"%}
    </form>
</div>
{% endblock %}